// src/routes/account/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Button } from '$lib/components/ui/button';
	import * as Card from '$lib/components/ui/card';
	import { storage } from '$lib/state';
	import { supabase } from '$lib/supabase';
	import { LogOut, User } from '@lucide/svelte';
</script>

<div class="h-[calc(100vh-48px)] overflow-y-auto px-3 pt-3 pb-6">
	<div class="mb-4 text-2xl font-semibold">Account</div>

	{#if $storage.auth}
		<Card.Root class="mb-3 flex flex-row items-center gap-3 px-4 py-3">
			<div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-muted">
				<User class="h-7 w-7" />
			</div>
			<div class="min-w-0 flex-1">
				<div class="truncate font-semibold">
					{$storage.auth.user.user_metadata?.full_name ?? $storage.auth.user.email ?? 'User'}
				</div>
				<div class="truncate text-sm text-muted-foreground">{$storage.auth.user.email}</div>
			</div>
		</Card.Root>

		<Button
			variant="outline"
			class="w-full justify-start gap-2 border-destructive/40 text-destructive hover:bg-destructive/10 hover:text-destructive"
			onclick={async () => {
				await supabase.auth.signOut();
				storage.update((s) => {
					s.auth = null;
					s.onboarding.account = false;
					return s;
				});
				await goto('/onboarding');
			}}
		>
			<LogOut class="h-4 w-4" />
			Sign out
		</Button>
	{:else}
		<Card.Root class="px-4 py-3">
			<div class="text-muted-foreground">Not signed in</div>
		</Card.Root>
	{/if}
</div>

// expo/app/(tabs)/account.tsx
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { LogOut, User } from 'lucide-react-native';
import { colors, font, spacing, radius } from '../../lib/theme';
import { supabase } from '../../lib/supabase';
import { useStorage } from '../../lib/state/storage';

export default function AccountScreen() {
	const { auth, setAuth } = useStorage();

	const handleSignOut = () => {
		Alert.alert('Sign out', 'Are you sure you want to sign out?', [
			{ text: 'Cancel', style: 'cancel' },
			{
				text: 'Sign out',
				style: 'destructive',
				onPress: async () => {
					await supabase.auth.signOut();
					setAuth(null);
					router.replace('/onboarding');
				}
			}
		]);
	};

	return (
		<SafeAreaView style={styles.safe} edges={['top']}>
			<ScrollView style={styles.scroll} contentContainerStyle={styles.content}>
				<Text style={styles.heading}>Account</Text>

				{auth ? (
					<View style={styles.card}>
						<View style={styles.avatar}>
							<User size={28} color={colors.foreground} />
						</View>
						<View style={styles.info}>
							<Text style={styles.name}>
								{auth.user.user_metadata?.full_name ?? auth.user.email ?? 'User'}
							</Text>
							<Text style={styles.email}>{auth.user.email}</Text>
						</View>
					</View>
				) : (
					<View style={styles.card}>
						<Text style={styles.noAccount}>Not signed in</Text>
					</View>
				)}

				{auth && (
					<TouchableOpacity style={styles.signOutBtn} onPress={handleSignOut}>
						<LogOut size={18} color={colors.destructive} />
						<Text style={styles.signOutText}>Sign out</Text>
					</TouchableOpacity>
				)}
			</ScrollView>
		</SafeAreaView>
	);
}

const styles = StyleSheet.create({
	safe: { flex: 1, backgroundColor: colors.background },
	scroll: { flex: 1 },
	content: { padding: spacing.md, paddingBottom: spacing['3xl'] },
	heading: {
		fontSize: font['2xl'],
		fontWeight: '600',
		color: colors.foreground,
		marginBottom: spacing.lg
	},
	card: {
		backgroundColor: colors.card,
		borderRadius: radius.lg,
		borderWidth: 1,
		borderColor: colors.border,
		padding: spacing.md,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12
	},
	avatar: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: colors.muted,
		alignItems: 'center',
		justifyContent: 'center'
	},
	info: { flex: 1 },
	name: { fontSize: font.base, fontWeight: '600', color: colors.foreground },
	email: { fontSize: font.sm, color: colors.mutedForeground, marginTop: 2 },
	noAccount: { color: colors.mutedForeground },
	signOutBtn: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
		marginTop: spacing.md,
		backgroundColor: colors.card,
		borderRadius: radius.lg,
		borderWidth: 1,
		borderColor: colors.border,
		padding: spacing.md
	},
	signOutText: { fontSize: font.base, color: colors.destructive }
});
