// src/routes/favorites/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import * as Card from '$lib/components/ui/card';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import { re } from '$lib/robotevents';
	import { storage } from '$lib/state';
	import { ArrowRight, Star } from '@lucide/svelte';

	let loading = $state(false);
	let teams = $state<re.models.Team[]>([]);
	let events = $state<re.models.Event[]>([]);

	$effect(() => {
		const favoriteTeams = $storage.favorites.teams;
		const favoriteEvents = $storage.favorites.events;

		if (favoriteTeams.length === 0 && favoriteEvents.length === 0) {
			teams = [];
			events = [];
			return;
		}

		let cancelled = false;
		loading = true;

		(async () => {
			const [teamResults, eventResults] = await Promise.allSettled([
				Promise.all(favoriteTeams.map((id) => re.team.teamGetTeam({ id }))),
				Promise.all(favoriteEvents.map((id) => re.events.eventGetEvent({ id })))
			]);

			if (cancelled) return;

			if (teamResults.status === 'fulfilled') teams = teamResults.value;
			if (eventResults.status === 'fulfilled') events = eventResults.value;
			loading = false;
		})();

		return () => {
			cancelled = true;
		};
	});

	const formatEventDate = (event: re.models.Event) => {
		if (!event.start && !event.end) return 'Date TBD';
		if (event.start && event.end) {
			if (event.start.toDateString() === event.end.toDateString())
				return event.start.toLocaleDateString();
			return `${event.start.toLocaleDateString()} - ${event.end.toLocaleDateString()}`;
		}
		return (event.start ?? event.end!).toLocaleDateString();
	};

	let isEmpty = $derived(
		$storage.favorites.teams.length === 0 && $storage.favorites.events.length === 0
	);
</script>

<div class="h-[calc(100vh-48px)] overflow-y-auto px-3 pt-3 pb-6">
	<div class="mb-4 text-2xl font-semibold">Favorites</div>

	{#if loading}
		<div class="space-y-2">
			<Skeleton class="h-16 w-full rounded-xl" />
			<Skeleton class="h-16 w-full rounded-xl" />
		</div>
	{:else if isEmpty}
		<div class="flex flex-col items-center gap-2 pt-16">
			<Star class="h-8 w-8 text-muted-foreground" />
			<div class="text-lg font-medium">No favorites yet</div>
			<div class="text-center text-sm text-muted-foreground">
				Save teams and events to find them here.
			</div>
		</div>
	{:else}
		{#if events.length > 0}
			<div class="mb-4">
				<div class="mb-2 text-sm font-medium tracking-wide text-muted-foreground uppercase">
					Events
				</div>
				<div class="space-y-2">
					{#each events as event}
						<Card.Root
							class="cursor-pointer gap-2 px-4 py-3"
							onclick={() => goto(`/events/${event.id}`)}
						>
							<div class="flex items-center gap-3">
								<div class="min-w-0 flex-1">
									<div class="truncate font-medium">{event.name}</div>
									<div class="text-sm text-muted-foreground">
										{event.location?.city}, {event.location?.region}
									</div>
									<div class="text-xs text-muted-foreground">{formatEventDate(event)}</div>
								</div>
								<ArrowRight class="h-5 w-5 shrink-0 text-muted-foreground" />
							</div>
						</Card.Root>
					{/each}
				</div>
			</div>
		{/if}

		{#if teams.length > 0}
			<div class="mb-4">
				<div class="mb-2 text-sm font-medium tracking-wide text-muted-foreground uppercase">
					Teams
				</div>
				<div class="space-y-2">
					{#each teams as team}
						<Card.Root class="gap-1 px-4 py-3">
							<div class="text-xl font-semibold">{team.number}</div>
							<div class="text-sm text-muted-foreground">
								{team.teamName ?? team.organization ?? ''}
							</div>
						</Card.Root>
					{/each}
				</div>
			</div>
		{/if}
	{/if}
</div>

// expo/app/(tabs)/favorites.tsx
import { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { ArrowRight, Star } from 'lucide-react-native';
import { colors, font, spacing, radius } from '../../lib/theme';
import { re } from '../../lib/robotevents';
import type { Event, Team } from '../../lib/robotevents/robotevents/models';
import { useStorage } from '../../lib/state/storage';

export default function FavoritesScreen() {
  const { favorites } = useStorage();
  const [teams, setTeams] = useState<Team[]>([]);
  const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (favorites.teams.length === 0 && favorites.events.length === 0) {
      setTeams([]);
      setEvents([]);
      return;
    }

    let cancelled = false;
    setLoading(true);

    const load = async () => {
      const [teamResults, eventResults] = await Promise.allSettled([
        Promise.all(favorites.teams.map((id) => re.team.teamGetTeam({ id }))),
        Promise.all(favorites.events.map((id) => re.events.eventGetEvent({ id }))),
      ]);

      if (cancelled) return;

      if (teamResults.status === 'fulfilled') setTeams(teamResults.value);
      if (eventResults.status === 'fulfilled') setEvents(eventResults.value);
      setLoading(false);
    };

    load();
    return () => { cancelled = true; };
  }, [favorites.teams.join(','), favorites.events.join(',')]);

  const isEmpty = favorites.teams.length === 0 && favorites.events.length === 0;

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <ScrollView style={styles.scroll} contentContainerStyle={styles.content}>
        <Text style={styles.heading}>Favorites</Text>

        {loading && <ActivityIndicator color={colors.primary} style={{ marginTop: 20 }} />}

        {!loading && isEmpty && (
          <View style={styles.emptyBox}>
            <Star size={32} color={colors.mutedForeground} />
            <Text style={styles.emptyText}>No favorites yet</Text>
            <Text style={styles.emptySubtext}>
              Save teams and events to find them here.
            </Text>
          </View>
        )}

        {!loading && events.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionLabel}>Events</Text>
            {events.map((event) => (
              <TouchableOpacity
                key={event.id}
                style={[styles.card, { marginBottom: 8 }]}
                onPress={() => router.push(`/events/${event.id}`)}
              >
                <View style={styles.cardRow}>
                  <View style={{ flex: 1 }}>
                    <Text style={styles.eventName} numberOfLines={2}>{event.name}</Text>
                    <Text style={styles.eventMeta}>
                      {event.location?.city}, {event.location?.region}
                    </Text>
                  </View>
                  <ArrowRight size={16} color={colors.mutedForeground} />
                </View>
              </TouchableOpacity>
            ))}
          </View>
        )}

        {!loading && teams.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionLabel}>Teams</Text>
            {teams.map((team) => (
              <View key={team.id} style={[styles.card, { marginBottom: 8 }]}>
                <Text style={styles.teamNum}>{team.number}</Text>
                <Text style={styles.teamName}>{team.teamName ?? team.organization ?? ''}</Text>
              </View>
            ))}
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  scroll: { flex: 1 },
  content: { padding: spacing.md, paddingBottom: spacing['3xl'] },
  heading: { fontSize: font['2xl'], fontWeight: '600', color: colors.foreground, marginBottom: spacing.lg },
  section: { marginBottom: spacing.xl },
  sectionLabel: {
    fontSize: font.sm,
    fontWeight: '500',
    color: colors.mutedForeground,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
  },
  cardRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  eventName: { fontSize: font.base, fontWeight: '500', color: colors.foreground },
  eventMeta: { fontSize: font.sm, color: colors.mutedForeground, marginTop: 2 },
  teamNum: { fontSize: font.xl, fontWeight: '600', color: colors.foreground },
  teamName: { fontSize: font.sm, color: colors.mutedForeground, marginTop: 2 },
  emptyBox: { alignItems: 'center', marginTop: 64, gap: 8 },
  emptyText: { fontSize: font.lg, fontWeight: '500', color: colors.foreground },
  emptySubtext: { fontSize: font.sm, color: colors.mutedForeground, textAlign: 'center' },
});
