// src/routes/events/[id]/+page.svelte
<script lang="ts">
	import {
		re,
		calculateOprDprCcwm,
		robotEventsMatchesToScoredMatches,
		type RatingsResult
	} from '$lib/robotevents';
	import { Button } from '$lib/components/ui/button';
	import * as ButtonGroup from '$lib/components/ui/button-group';
	import * as Select from '$lib/components/ui/select';
	import InfoTab from './InfoTab.svelte';
	import RankingsTab from './RankingsTab.svelte';
	import ScheduleTab from './ScheduleTab.svelte';
	import SkillsTab from './SkillsTab.svelte';
	import TeamDrawer from './TeamDrawer.svelte';
	import MatchDrawer from './MatchDrawer.svelte';
	import { ArrowLeft, Clock3, Gamepad2, Info, ListOrdered, Search, Users } from '@lucide/svelte';

	import { page } from '$app/state';

	const tabs = ['schedule', 'rankings', 'skills', 'info'] as const;
	type EventTab = (typeof tabs)[number];

	const tabLabels: Record<EventTab, string> = {
		schedule: 'Schedule',
		rankings: 'Rankings',
		skills: 'Skills',
		info: 'Info'
	};

	const tabMeta = [
		{ key: 'schedule' as const, label: 'Schedule', icon: Clock3 },
		{ key: 'rankings' as const, label: 'Rankings', icon: ListOrdered },
		{ key: 'skills' as const, label: 'Skills', icon: Gamepad2 },
		{ key: 'info' as const, label: 'Info', icon: Info }
	];

	type ScheduleRow = {
		group: 'practice' | 'qualifier' | 'elimination';
		match: string;
		time: string;
		score: string;
		red: string[];
		blue: string[];
		field?: string;
		played: boolean;
	};

	type RankingRow = {
		rank: number;
		team: string;
		name: string;
		wins: number;
		losses: number;
		ties: number;
		wp: number;
		ap: number;
		sp: number;
	};

	type SkillsRow = {
		rank: number;
		team: string;
		name: string;
		points: number;
		driver: number;
		driverRuns: number;
		auton: number;
		autonRuns: number;
	};

	type EventInfo = {
		name: string;
		locationLine1: string;
		locationLine2: string;
		date: string;
		division: string;
	};

	type TeamLookup = {
		number: string;
		name: string;
	};

	const fallbackInfoData: EventInfo = {
		name: 'Event',
		locationLine1: 'Location TBD',
		locationLine2: '',
		date: 'Date TBD',
		division: 'Division'
	};

	const parseDivisionId = (value: string): number | null => {
		const parsed = Number.parseInt(value, 10);
		return Number.isFinite(parsed) ? parsed : null;
	};

	let eventId = $derived(Number.parseInt(page.params.id ?? '', 10));
	let eventMeta = $state<re.models.Event | null>(null);
	let divisions = $state<re.models.Division[]>([]);
	let selectableDivisions = $derived(
		divisions.filter(
			(division): division is re.models.Division & { id: number } => typeof division.id === 'number'
		)
	);
	let selectedDivisionValue = $state('');
	let selectedDivisionId = $derived(parseDivisionId(selectedDivisionValue));
	let selectedDivisionName = $derived(
		selectableDivisions.find((division) => division.id.toString() === selectedDivisionValue)
			?.name ?? 'Division'
	);
	let teamLookup = $state<Map<number, TeamLookup>>(new Map());
	let allSkills = $state<re.models.Skill[]>([]);
	let awards = $state<re.models.Award[]>([]);
	let scheduleRows = $state<ScheduleRow[]>([]);
	let rankingRows = $state<RankingRow[]>([]);
	let skillsRows = $state<SkillsRow[]>([]);
	let divisionMatches = $state<re.models.MatchObj[]>([]);
	let divisionRatings = $derived.by(() => {
		const qualMatches = divisionMatches.filter((m) => m.round === 2);
		if (qualMatches.length === 0) return null;
		return calculateOprDprCcwm(
			robotEventsMatchesToScoredMatches(qualMatches, { includeUnscored: true })
		);
	});
	let teamNumberToId = $derived(
		new Map<string, number>(
			[...teamLookup.entries()].map(([id, info]) => [info.number.toLowerCase(), id])
		)
	);
	let infoData = $state<EventInfo>(fallbackInfoData);
	let isLoadingEvent = $state(false);
	let isLoadingDivision = $state(false);
	let isLoading = $derived(isLoadingEvent || isLoadingDivision);
	let loadError = $state<string | null>(null);
	let isTeamDrawerOpen = $state(false);
	let selectedRankingTeam = $state<RankingRow | null>(null);
	let isMatchDrawerOpen = $state(false);
	let selectedMatchRow = $state<ScheduleRow | null>(null);

	const normalizeTeam = (value: string) => value.trim().toLowerCase();
	let selectedTeamKey = $derived(
		selectedRankingTeam ? normalizeTeam(selectedRankingTeam.team) : null
	);

	let selectedTeamRatings = $derived.by(
		(): { opr: number | null; dpr: number | null; ccwm: number | null } => {
			if (!selectedTeamKey || !divisionRatings) return { opr: null, dpr: null, ccwm: null };
			const teamId = teamNumberToId.get(selectedTeamKey);
			if (teamId === undefined) return { opr: null, dpr: null, ccwm: null };
			const opr = divisionRatings.opr[teamId] ?? null;
			const dpr = divisionRatings.dpr[teamId] ?? null;
			const ccwm = divisionRatings.ccwm[teamId] ?? null;
			return { opr, dpr, ccwm };
		}
	);

	let selectedTeamSkills = $derived(
		selectedTeamKey
			? (skillsRows.find((row) => normalizeTeam(row.team) === selectedTeamKey) ?? null)
			: null
	);
	let selectedTeamMatches = $derived(
		selectedTeamKey
			? scheduleRows.filter(
					(row) =>
						row.red.some((team) => normalizeTeam(team) === selectedTeamKey) ||
						row.blue.some((team) => normalizeTeam(team) === selectedTeamKey)
				)
			: []
	);

	const formatDate = (value: Date) =>
		new Intl.DateTimeFormat('en-US', {
			weekday: 'short',
			month: 'short',
			day: 'numeric',
			year: 'numeric'
		}).format(value);

	const formatDateRange = (start?: Date, end?: Date) => {
		if (!start && !end) return 'Date TBD';
		if (start && end) {
			if (start.toDateString() === end.toDateString()) return formatDate(start);
			return `${formatDate(start)} - ${formatDate(end)}`;
		}
		return formatDate(start ?? end!);
	};

	const formatTime = (value?: Date) => {
		if (!value) return 'TBD';
		return new Intl.DateTimeFormat('en-US', {
			hour: 'numeric',
			minute: '2-digit'
		}).format(value);
	};

	const toErrorMessage = (error: unknown) => {
		if (error instanceof Error && error.message.length > 0) return error.message;
		return 'Unable to load event data.';
	};

	const buildInfoData = (event: re.models.Event, division: string): EventInfo => {
		const locationLine1 = [
			event.location?.venue,
			event.location?.address1,
			event.location?.address2
		]
			.filter((value) => Boolean(value && value.trim().length > 0))
			.join(', ');
		const locationLine2 = [event.location?.city, event.location?.region, event.location?.country]
			.filter((value) => Boolean(value && value.trim().length > 0))
			.join(', ');

		return {
			name: event.name,
			locationLine1: locationLine1.length > 0 ? locationLine1 : 'Location TBD',
			locationLine2,
			date: formatDateRange(event.start, event.end),
			division
		};
	};

	const buildTeamLookup = (teams: re.models.Team[]) =>
		new Map<number, TeamLookup>(
			teams.map((team) => [
				team.id,
				{
					number: team.number,
					name: (team.teamName ?? '').trim()
				}
			])
		);

	const mapMatches = (matches: re.models.MatchObj[]): ScheduleRow[] => {
		const getSortTime = (match: re.models.MatchObj) =>
			match.scheduled?.getTime() ?? match.started?.getTime() ?? null;

		const getMatchGroup = (match: re.models.MatchObj): 'practice' | 'qualifier' | 'elimination' => {
			if (match.round === 1) return 'practice';
			if (match.round === 2) return 'qualifier';
			if (match.round >= 3) return 'elimination';

			const normalized = (match.name ?? '').replace(/\s+/g, ' ').trim().toLowerCase();
			if (normalized.startsWith('practice')) return 'practice';
			if (normalized.startsWith('qualifier') || normalized.startsWith('qualification')) {
				return 'qualifier';
			}
			return 'elimination';
		};

		const formatMatchName = (match: re.models.MatchObj) => {
			const raw = match.name?.trim() ?? '';
			if (raw.length > 0) {
				const normalized = raw.replace(/\s+/g, ' ').trim();

				const practice = normalized.match(/^practice\s*#?\s*(\d+)$/i);
				if (practice) return `P${practice[1]}`;

				const qualifier = normalized.match(/^(?:qualifier|qualification)\s*#?\s*(\d+)$/i);
				if (qualifier) return `Q${qualifier[1]}`;

				const parseElim = (pattern: RegExp, prefix: string) => {
					const parsed = normalized.match(pattern);
					if (!parsed) return null;
					const instance = parsed[1] ?? `${match.instance || 1}`;
					const matchNum = parsed[2] ?? `${match.matchnum || 1}`;
					return `${prefix} ${instance}-${matchNum}`;
				};

				const r16 = parseElim(/^(?:round\s*of\s*16|r16)\s*#?\s*(\d+)(?:\s*-\s*(\d+))?$/i, 'R16');
				if (r16) return r16;

				const qf = parseElim(
					/^(?:quarter\s*final|quarterfinal|qf)\s*#?\s*(\d+)(?:\s*-\s*(\d+))?$/i,
					'QF'
				);
				if (qf) return qf;

				const sf = parseElim(
					/^(?:semi\s*final|semifinal|sf)\s*#?\s*(\d+)(?:\s*-\s*(\d+))?$/i,
					'SF'
				);
				if (sf) return sf;

				const finals = parseElim(/^(?:final|finals|f)\s*#?\s*(\d+)(?:\s*-\s*(\d+))?$/i, 'F');
				if (finals) return finals;

				return normalized;
			}

			const labelByRound: Record<number, string> = {
				1: 'P',
				2: 'Q',
				3: 'QF',
				4: 'SF',
				5: 'F',
				6: 'R16'
			};

			const label = labelByRound[match.round] ?? `Round ${match.round}`;
			if (match.round === 2) return `${label}${match.matchnum}`;
			if (match.round >= 3 && match.instance > 0)
				return `${label} ${match.instance}-${match.matchnum}`;
			return `${label} ${match.matchnum}`;
		};

		return [...matches]
			.sort((a, b) => {
				const leftTime = getSortTime(a);
				const rightTime = getSortTime(b);
				if (leftTime !== null && rightTime !== null && leftTime !== rightTime) {
					return leftTime - rightTime;
				}
				if (leftTime !== null && rightTime === null) return -1;
				if (leftTime === null && rightTime !== null) return 1;

				if (a.round !== b.round) return a.round - b.round;
				if (a.instance !== b.instance) return a.instance - b.instance;
				return a.matchnum - b.matchnum;
			})
			.map((match) => {
				const redAlliance = match.alliances.find(
					(alliance) => alliance.color?.toLowerCase() === 'red'
				);
				const blueAlliance = match.alliances.find(
					(alliance) => alliance.color?.toLowerCase() === 'blue'
				);

				const redScore = redAlliance?.score ?? 0;
				const blueScore = blueAlliance?.score ?? 0;

				return {
					group: getMatchGroup(match),
					match: formatMatchName(match),
					time: formatTime(match.scheduled ?? match.started),
					score: `${redScore} - ${blueScore}`,
					red: (redAlliance?.teams ?? []).map(
						(team) => team.team?.name ?? team.team?.code ?? '---'
					),
					blue: (blueAlliance?.teams ?? []).map(
						(team) => team.team?.name ?? team.team?.code ?? '---'
					),
					field: match.field,
					played: match.started != null
				};
			});
	};

	const mapRankings = (
		rankings: re.models.Ranking[],
		teams: Map<number, TeamLookup>
	): RankingRow[] =>
		[...rankings]
			.sort((a, b) => (a.rank ?? Number.MAX_SAFE_INTEGER) - (b.rank ?? Number.MAX_SAFE_INTEGER))
			.map((ranking) => {
				const teamId = ranking.team?.id;
				const team = teamId ? teams.get(teamId) : undefined;
				const fallbackNumber = ranking.team?.name ?? ranking.team?.code ?? '---';
				const fallbackName = ranking.team?.code ?? '';

				return {
					rank: ranking.rank ?? 0,
					team: team?.number ?? fallbackNumber,
					name: team?.name || fallbackName,
					wins: ranking.wins ?? 0,
					losses: ranking.losses ?? 0,
					ties: ranking.ties ?? 0,
					wp: ranking.wp ?? 0,
					ap: ranking.ap ?? 0,
					sp: ranking.sp ?? 0
				};
			});

	const mapSkills = (skills: re.models.Skill[], teams: Map<number, TeamLookup>): SkillsRow[] => {
		const aggregates = new Map<
			number,
			{
				teamId: number;
				driver: number;
				auton: number;
				driverRuns: number;
				autonRuns: number;
			}
		>();

		for (const skill of skills) {
			const teamId = skill.team?.id;
			if (!teamId) continue;

			const current =
				aggregates.get(teamId) ??
				({ teamId, driver: 0, auton: 0, driverRuns: 0, autonRuns: 0 } as const);

			const score = skill.score ?? 0;
			const attempts = skill.attempts ?? 0;

			if (skill.type === re.models.SkillType.Driver) {
				aggregates.set(teamId, {
					...current,
					driver: Math.max(current.driver, score),
					driverRuns: Math.max(current.driverRuns, attempts)
				});
				continue;
			}

			if (skill.type === re.models.SkillType.Programming) {
				aggregates.set(teamId, {
					...current,
					auton: Math.max(current.auton, score),
					autonRuns: Math.max(current.autonRuns, attempts)
				});
			}
		}

		const sorted = [...aggregates.values()]
			.map((aggregate) => {
				const team = teams.get(aggregate.teamId);
				const points = aggregate.driver + aggregate.auton;

				return {
					team: team?.number ?? `${aggregate.teamId}`,
					name: team?.name ?? '',
					points,
					driver: aggregate.driver,
					driverRuns: aggregate.driverRuns,
					auton: aggregate.auton,
					autonRuns: aggregate.autonRuns
				};
			})
			.sort((a, b) => {
				if (b.points !== a.points) return b.points - a.points;
				if (b.driver !== a.driver) return b.driver - a.driver;
				return b.auton - a.auton;
			});

		return sorted.map((row, index) => ({ ...row, rank: index + 1 }));
	};

	$effect(() => {
		const id = eventId;

		if (!Number.isFinite(id) || id <= 0) {
			loadError = 'Invalid event id.';
			isLoadingEvent = false;
			isLoadingDivision = false;
			eventMeta = null;
			divisions = [];
			selectedDivisionValue = '';
			teamLookup = new Map();
			allSkills = [];
			scheduleRows = [];
			rankingRows = [];
			skillsRows = [];
			infoData = fallbackInfoData;
			isTeamDrawerOpen = false;
			selectedRankingTeam = null;
			return;
		}

		let cancelled = false;
		isLoadingEvent = true;
		loadError = null;

		const loadEvent = async () => {
			try {
				const [event, teams, skills, eventAwards] = await Promise.all([
					re.events.eventGetEvent({ id }),
					re.depaginate(
						re.events.eventGetTeams({ id }, re.custom.maxPages),
						re.models.PaginatedTeamFromJSON
					),
					re.depaginate(
						re.events.eventGetSkills({ id }, re.custom.maxPages),
						re.models.PaginatedSkillFromJSON
					),
					re
						.depaginate(
							re.events.eventGetAwards({ id }, re.custom.maxPages),
							re.models.PaginatedAwardFromJSON
						)
						.catch(() => [] as re.models.Award[])
				]);

				if (cancelled) return;

				eventMeta = event;
				const sortedDivisions = [...(event.divisions ?? [])].sort(
					(a, b) => (a.order ?? 0) - (b.order ?? 0)
				);
				divisions = sortedDivisions;

				const divisionExists = selectableDivisions.some(
					(division) => division.id.toString() === selectedDivisionValue
				);
				selectedDivisionValue = divisionExists
					? selectedDivisionValue
					: (selectableDivisions[0]?.id.toString() ?? '');

				teamLookup = buildTeamLookup(teams);
				allSkills = skills;
				awards = eventAwards;
				infoData = buildInfoData(event, sortedDivisions[0]?.name ?? 'Division');
			} catch (error) {
				if (cancelled) return;

				loadError = toErrorMessage(error);
				eventMeta = null;
				divisions = [];
				selectedDivisionValue = '';
				teamLookup = new Map();
				allSkills = [];
				awards = [];
				scheduleRows = [];
				rankingRows = [];
				skillsRows = [];
				infoData = fallbackInfoData;
				isTeamDrawerOpen = false;
				selectedRankingTeam = null;
			} finally {
				if (!cancelled) {
					isLoadingEvent = false;
				}
			}
		};

		void loadEvent();

		return () => {
			cancelled = true;
		};
	});

	$effect(() => {
		const id = eventId;
		const event = eventMeta;
		const divisionId = selectedDivisionId;
		const teams = teamLookup;
		const skills = allSkills;

		if (!event || !Number.isFinite(id) || id <= 0) return;

		const divisionName =
			selectableDivisions.find((division) => division.id.toString() === selectedDivisionValue)
				?.name ?? 'Division';
		infoData = buildInfoData(event, divisionName);

		const filteredSkills =
			divisionId === null ? skills : skills.filter((skill) => skill.division?.id === divisionId);
		skillsRows = mapSkills(filteredSkills.length > 0 ? filteredSkills : skills, teams);

		if (divisionId === null) {
			scheduleRows = [];
			rankingRows = [];
			divisionMatches = [];
			isLoadingDivision = false;
			isTeamDrawerOpen = false;
			selectedRankingTeam = null;
			return;
		}

		let cancelled = false;
		isLoadingDivision = true;

		const loadDivision = async () => {
			try {
				const [rankings, matches] = await Promise.all([
					re.depaginate(
						re.events.eventGetDivisionRankings({ id, div: divisionId }, re.custom.maxPages),
						re.models.PaginatedRankingFromJSON
					),
					re.depaginate(
						re.events.eventGetDivisionMatches({ id, div: divisionId }, re.custom.maxPages),
						re.models.PaginatedMatchFromJSON
					)
				]);

				if (cancelled) return;

				rankingRows = mapRankings(rankings, teams);
				scheduleRows = mapMatches(matches);
				divisionMatches = matches;
			} catch (error) {
				if (cancelled) return;

				loadError = toErrorMessage(error);
				rankingRows = [];
				scheduleRows = [];
				divisionMatches = [];
				isTeamDrawerOpen = false;
				selectedRankingTeam = null;
			} finally {
				if (!cancelled) {
					isLoadingDivision = false;
				}
			}
		};

		void loadDivision();

		return () => {
			cancelled = true;
		};
	});

	let activeIndex = $state(0);
	let dragOffset = $state(0);
	let dragging = $state(false);
	let paneWidth = $state(1);
	const paneGap = 20;
	let panesRef = $state<HTMLElement | null>(null);
	let contentScrollRef = $state<HTMLElement | null>(null);
	let schedulePaneRef = $state<HTMLElement | null>(null);
	let rankingsPaneRef = $state<HTMLElement | null>(null);
	let skillsPaneRef = $state<HTMLElement | null>(null);
	let infoPaneRef = $state<HTMLElement | null>(null);
	let paneHeight = $state(1);

	const resetContentScroll = () => {
		if (!contentScrollRef) return;
		contentScrollRef.scrollTop = 0;
	};

	let activeTab = $derived(tabs[activeIndex]);
	let activeTitle = $derived(tabLabels[activeTab]);

	$effect(() => {
		const currentTeam = selectedRankingTeam;
		if (!currentTeam) return;
		const currentTeamKey = normalizeTeam(currentTeam.team);

		const next = rankingRows.find((row) => normalizeTeam(row.team) === currentTeamKey) ?? null;

		if (!next) {
			isTeamDrawerOpen = false;
			selectedRankingTeam = null;
			return;
		}

		if (
			next.rank !== currentTeam.rank ||
			next.wins !== currentTeam.wins ||
			next.losses !== currentTeam.losses ||
			next.ties !== currentTeam.ties ||
			next.wp !== currentTeam.wp ||
			next.ap !== currentTeam.ap ||
			next.sp !== currentTeam.sp ||
			next.name !== currentTeam.name
		) {
			selectedRankingTeam = next;
		}
	});

	$effect(() => {
		if (!panesRef) return;

		paneWidth = panesRef.clientWidth || 1;
		const observer = new ResizeObserver(() => {
			paneWidth = panesRef?.clientWidth || 1;
		});

		observer.observe(panesRef);

		return () => {
			observer.disconnect();
		};
	});

	$effect(() => {
		const activePane = [schedulePaneRef, rankingsPaneRef, skillsPaneRef, infoPaneRef][activeIndex];
		if (!activePane) return;

		const sync = () => {
			const h = Math.max(1, activePane.scrollHeight || 1);
			if (h !== paneHeight) paneHeight = h;
		};

		const frame = requestAnimationFrame(sync);
		const observer = new ResizeObserver(sync);
		observer.observe(activePane);

		return () => {
			cancelAnimationFrame(frame);
			observer.disconnect();
		};
	});

	const goToTab = (tab: EventTab) => {
		const index = tabs.indexOf(tab);
		if (index === activeIndex) return;
		activeIndex = index;
		dragOffset = 0;
		dragging = false;
		resetContentScroll();
	};

	const applyEdgeResistance = (offset: number) => {
		if (activeIndex === 0 && offset > 0) return offset * 0.35;
		if (activeIndex === tabs.length - 1 && offset < 0) return offset * 0.35;
		return offset;
	};

	const settleSwipe = () => {
		const threshold = paneWidth * 0.2;
		const initialIndex = activeIndex;
		let targetIndex = activeIndex;

		if (dragOffset <= -threshold) targetIndex = activeIndex + 1;
		else if (dragOffset >= threshold) targetIndex = activeIndex - 1;

		if (targetIndex < 0 || targetIndex >= tabs.length) {
			targetIndex = activeIndex;
		}

		activeIndex = targetIndex;
		dragOffset = 0;
		dragging = false;

		if (targetIndex !== initialIndex) {
			resetContentScroll();
		}
	};

	const swipeNavigation = (node: HTMLElement) => {
		let startX = 0;
		let startY = 0;
		let tracking = false;
		let horizontal = false;

		const onStart = (event: TouchEvent) => {
			const touch = event.changedTouches[0];
			if (!touch) return;

			startX = touch.clientX;
			startY = touch.clientY;
			tracking = true;
			horizontal = false;
			dragging = true;
			dragOffset = 0;
		};

		const onMove = (event: TouchEvent) => {
			if (!tracking) return;

			const touch = event.changedTouches[0];
			if (!touch) return;

			const deltaX = touch.clientX - startX;
			const deltaY = touch.clientY - startY;

			if (!horizontal) {
				if (Math.abs(deltaX) < 8 && Math.abs(deltaY) < 8) return;
				if (Math.abs(deltaX) <= Math.abs(deltaY)) {
					tracking = false;
					dragging = false;
					dragOffset = 0;
					return;
				}
				horizontal = true;
			}

			event.preventDefault();
			dragOffset = applyEdgeResistance(deltaX);
		};

		const onEnd = () => {
			if (!tracking && !dragging) return;
			tracking = false;

			if (!horizontal) {
				dragging = false;
				dragOffset = 0;
				return;
			}

			settleSwipe();
		};

		node.addEventListener('touchstart', onStart, { passive: true });
		node.addEventListener('touchmove', onMove, { passive: false });
		node.addEventListener('touchend', onEnd, { passive: true });
		node.addEventListener('touchcancel', onEnd, { passive: true });

		return {
			destroy: () => {
				node.removeEventListener('touchstart', onStart);
				node.removeEventListener('touchmove', onMove);
				node.removeEventListener('touchend', onEnd);
				node.removeEventListener('touchcancel', onEnd);
			}
		};
	};

	const openTeamDrawer = (row: RankingRow) => {
		selectedRankingTeam = row;
		isTeamDrawerOpen = true;
	};

	const openMatchDrawer = (row: ScheduleRow) => {
		selectedMatchRow = row;
		isMatchDrawerOpen = true;
	};
</script>

<div class="flex h-full flex-col overflow-hidden bg-background">
	<div class="px-4 pt-5 pb-2">
		<div class="mb-2 flex items-center justify-between">
			<Button
				variant="ghost"
				size="icon"
				onclick={() => window.history.back()}
				class="h-10 w-10 rounded-full text-foreground/90"
			>
				<ArrowLeft class="h-9 w-9" />
			</Button>
			<div class="flex items-center gap-2 text-muted-foreground">
				<Users class="h-5 w-5" />
				<Select.Root type="single" bind:value={selectedDivisionValue}>
					<Select.Trigger class="h-9 min-w-44 border-border bg-card text-sm text-foreground">
						{selectedDivisionName}
					</Select.Trigger>
					<Select.Content>
						{#each selectableDivisions as division}
							<Select.Item value={division.id.toString()}>{division.name}</Select.Item>
						{/each}
					</Select.Content>
				</Select.Root>
			</div>
		</div>
	</div>

	<div bind:this={contentScrollRef} class="min-h-0 flex-1 overflow-y-auto">
		<div class="px-4 pb-2">
			<div class="flex items-center justify-between">
				<h1 class="text-2xl leading-none font-semibold tracking-tight">{activeTitle}</h1>
				<Button variant="ghost" size="icon" class="h-10 w-10 text-muted-foreground">
					<Search class="h-7 w-7" />
				</Button>
			</div>
		</div>

		<div class="sticky top-0 z-10 bg-black">
			<div class="rounded-t-4xl border-t border-border/70 bg-card px-4 pt-4">
				<div class=" -mx-4 bg-card px-4 pt-1 pb-4">
					<ButtonGroup.Root class="w-full *:data-[slot=button]:h-12 *:data-[slot=button]:flex-1">
						{#each tabMeta as tab}
							<Button
								variant="outline"
								size="icon"
								onclick={() => goToTab(tab.key)}
								class={activeTab === tab.key
									? 'border-primary/60 bg-primary/20 text-primary'
									: 'border-border bg-card text-muted-foreground'}
							>
								<tab.icon class="h-6 w-6" stroke-width={2.25} />
							</Button>
						{/each}
					</ButtonGroup.Root>
				</div>
			</div>
		</div>
		<div class="bg-card px-4 pb-6">
			{#if isLoading}
				<div class="mb-3 px-1 text-sm text-muted-foreground">Loading event data...</div>
			{/if}

			{#if loadError}
				<div
					class="mb-3 rounded-2xl border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive"
				>
					{loadError}
				</div>
			{/if}

			<div
				bind:this={panesRef}
				class="overflow-hidden"
				style={`touch-action: pan-y; height: ${paneHeight}px;`}
				use:swipeNavigation
			>
				<div
					class="flex w-full items-start"
					style={`gap: ${paneGap}px; transform: translate3d(calc(${activeIndex * -100}% - ${activeIndex * paneGap}px + ${dragOffset}px), 0, 0); transition: ${dragging ? 'none' : 'transform 300ms cubic-bezier(0.22, 1, 0.36, 1)'};`}
				>
					<div bind:this={schedulePaneRef} class="w-full shrink-0">
						<ScheduleTab rows={scheduleRows} onMatchSelect={openMatchDrawer} />
					</div>
					<div bind:this={rankingsPaneRef} class="w-full shrink-0">
						<RankingsTab rows={rankingRows} onTeamSelect={openTeamDrawer} />
					</div>
					<div bind:this={skillsPaneRef} class="w-full shrink-0">
						<SkillsTab rows={skillsRows} />
					</div>
					<div bind:this={infoPaneRef} class="w-full shrink-0">
						<InfoTab
							info={infoData}
							teams={[...teamLookup.entries()].map(([id, t]) => ({
								id,
								number: t.number,
								name: t.name
							}))}
							{awards}
							{rankingRows}
							hasSchedule={scheduleRows.length > 0}
							season={eventMeta?.season?.id ?? 0}
							onTeamSelect={openTeamDrawer}
						/>
					</div>
				</div>
			</div>
		</div>
	</div>

	<TeamDrawer
		bind:open={isTeamDrawerOpen}
		team={selectedRankingTeam}
		skills={selectedTeamSkills}
		matches={selectedTeamMatches}
		opr={selectedTeamRatings.opr}
		dpr={selectedTeamRatings.dpr}
		ccwm={selectedTeamRatings.ccwm}
	/>
	<MatchDrawer bind:open={isMatchDrawerOpen} row={selectedMatchRow} {rankingRows} />
</div>

// scoutr-vrc/app/events/[id].tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import {
	View,
	Text,
	TouchableOpacity,
	ScrollView,
	StyleSheet,
	ActivityIndicator,
	Dimensions,
	NativeScrollEvent,
	NativeSyntheticEvent
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, Clock3, Gamepad2, Info, ListOrdered, Users } from 'lucide-react-native';
import { colors, font, spacing, radius } from '../../lib/theme';
import { re, calculateOprDprCcwm, robotEventsMatchesToScoredMatches } from '../../lib/robotevents';
import type {
	MatchObj,
	Ranking,
	Skill,
	Award,
	Team,
	Division
} from '../../lib/robotevents/robotevents/models';
import { SkillType } from '../../lib/robotevents/robotevents/models';
import { ScheduleTab } from '../../lib/components/events/ScheduleTab';
import { RankingsTab } from '../../lib/components/events/RankingsTab';
import { SkillsTab } from '../../lib/components/events/SkillsTab';
import { InfoTab } from '../../lib/components/events/InfoTab';
import { TeamDrawer } from '../../lib/components/events/TeamDrawer';
import { MatchDrawer } from '../../lib/components/events/MatchDrawer';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

type ScheduleRow = {
	group: 'practice' | 'qualifier' | 'elimination';
	match: string;
	time: string;
	score: string;
	red: string[];
	blue: string[];
	field?: string;
	played: boolean;
};

type RankingRow = {
	rank: number;
	team: string;
	name: string;
	wins: number;
	losses: number;
	ties: number;
	wp: number;
	ap: number;
	sp: number;
};

type SkillsRow = {
	rank: number;
	team: string;
	name: string;
	points: number;
	driver: number;
	driverRuns: number;
	auton: number;
	autonRuns: number;
};

type EventInfo = {
	name: string;
	locationLine1: string;
	locationLine2: string;
	date: string;
};

type TeamLookup = { number: string; name: string };

const tabs = ['schedule', 'rankings', 'skills', 'info'] as const;
type EventTab = (typeof tabs)[number];

const tabMeta: { key: EventTab; icon: typeof Clock3 }[] = [
	{ key: 'schedule', icon: Clock3 },
	{ key: 'rankings', icon: ListOrdered },
	{ key: 'skills', icon: Gamepad2 },
	{ key: 'info', icon: Info }
];

const fallbackInfo: EventInfo = {
	name: 'Event',
	locationLine1: 'Location TBD',
	locationLine2: '',
	date: 'Date TBD'
};

const formatDate = (v: Date) =>
	new Intl.DateTimeFormat('en-US', {
		weekday: 'short',
		month: 'short',
		day: 'numeric',
		year: 'numeric'
	}).format(v);

const formatDateRange = (start?: Date, end?: Date) => {
	if (!start && !end) return 'Date TBD';
	if (start && end) {
		if (start.toDateString() === end.toDateString()) return formatDate(start);
		return `${formatDate(start)} \u2013 ${formatDate(end)}`;
	}
	return formatDate(start ?? end!);
};

const formatTime = (v?: Date) => {
	if (!v) return 'TBD';
	return new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(v);
};

const buildInfoData = (
	event: Awaited<ReturnType<typeof re.events.eventGetEvent>>,
	division: string
): EventInfo => {
	const loc = event.location;
	const line1 = [loc?.venue, loc?.address1, loc?.address2]
		.filter((v) => Boolean(v?.trim()))
		.join(', ');
	const line2 = [loc?.city, loc?.region, loc?.country].filter((v) => Boolean(v?.trim())).join(', ');
	return {
		name: event.name,
		locationLine1: line1 || 'Location TBD',
		locationLine2: line2,
		date: formatDateRange(event.start, event.end)
	};
};

const buildTeamLookup = (teams: Team[]) =>
	new Map<number, TeamLookup>(
		teams.map((t) => [t.id, { number: t.number, name: (t.teamName ?? '').trim() }])
	);

const formatMatchName = (match: MatchObj): string => {
	const raw = match.name?.trim() ?? '';
	if (raw.length > 0) {
		const n = raw.replace(/\s+/g, ' ').trim();
		const practice = n.match(/^practice\s*#?\s*(\d+)$/i);
		if (practice) return `P${practice[1]}`;
		const qualifier = n.match(/^(?:qualifier|qualification)\s*#?\s*(\d+)$/i);
		if (qualifier) return `Q${qualifier[1]}`;
		const parseElim = (pattern: RegExp, prefix: string) => {
			const parsed = n.match(pattern);
			if (!parsed) return null;
			const inst = parsed[1] ?? `${match.instance || 1}`;
			const num = parsed[2] ?? `${match.matchnum || 1}`;
			return `${prefix} ${inst}-${num}`;
		};
		const r16 = parseElim(/^(?:round\s*of\s*16|r16)\s*#?\s*(\d+)(?:\s*-\s*(\d+))?$/i, 'R16');
		if (r16) return r16;
		const qf = parseElim(
			/^(?:quarter\s*final|quarterfinal|qf)\s*#?\s*(\d+)(?:\s*-\s*(\d+))?$/i,
			'QF'
		);
		if (qf) return qf;
		const sf = parseElim(/^(?:semi\s*final|semifinal|sf)\s*#?\s*(\d+)(?:\s*-\s*(\d+))?$/i, 'SF');
		if (sf) return sf;
		const finals = parseElim(/^(?:final|finals|f)\s*#?\s*(\d+)(?:\s*-\s*(\d+))?$/i, 'F');
		if (finals) return finals;
		return n;
	}
	const labels: Record<number, string> = { 1: 'P', 2: 'Q', 3: 'QF', 4: 'SF', 5: 'F', 6: 'R16' };
	const label = labels[match.round] ?? `Round ${match.round}`;
	if (match.round === 2) return `${label}${match.matchnum}`;
	if (match.round >= 3 && match.instance > 0) return `${label} ${match.instance}-${match.matchnum}`;
	return `${label} ${match.matchnum}`;
};

const getMatchGroup = (match: MatchObj): 'practice' | 'qualifier' | 'elimination' => {
	if (match.round === 1) return 'practice';
	if (match.round === 2) return 'qualifier';
	if (match.round >= 3) return 'elimination';
	const n = (match.name ?? '').replace(/\s+/g, ' ').trim().toLowerCase();
	if (n.startsWith('practice')) return 'practice';
	if (n.startsWith('qualifier') || n.startsWith('qualification')) return 'qualifier';
	return 'elimination';
};

const mapMatches = (matches: MatchObj[]): ScheduleRow[] => {
	const getTime = (m: MatchObj) => m.scheduled?.getTime() ?? m.started?.getTime() ?? null;
	return [...matches]
		.sort((a, b) => {
			const lt = getTime(a),
				rt = getTime(b);
			if (lt !== null && rt !== null && lt !== rt) return lt - rt;
			if (lt !== null && rt === null) return -1;
			if (lt === null && rt !== null) return 1;
			if (a.round !== b.round) return a.round - b.round;
			if (a.instance !== b.instance) return a.instance - b.instance;
			return a.matchnum - b.matchnum;
		})
		.map((match) => {
			const red = match.alliances.find((a) => a.color?.toLowerCase() === 'red');
			const blue = match.alliances.find((a) => a.color?.toLowerCase() === 'blue');
			return {
				group: getMatchGroup(match),
				match: formatMatchName(match),
				time: formatTime(match.scheduled ?? match.started),
				score: `${red?.score ?? 0} - ${blue?.score ?? 0}`,
				red: (red?.teams ?? []).map((t) => t.team?.name ?? t.team?.code ?? '---'),
				blue: (blue?.teams ?? []).map((t) => t.team?.name ?? t.team?.code ?? '---'),
				field: match.field,
				played: match.started != null
			};
		});
};

const mapRankings = (rankings: Ranking[], teams: Map<number, TeamLookup>): RankingRow[] =>
	[...rankings]
		.sort((a, b) => (a.rank ?? Number.MAX_SAFE_INTEGER) - (b.rank ?? Number.MAX_SAFE_INTEGER))
		.map((r) => {
			const team = r.team?.id ? teams.get(r.team.id) : undefined;
			return {
				rank: r.rank ?? 0,
				team: team?.number ?? r.team?.name ?? r.team?.code ?? '---',
				name: team?.name ?? r.team?.code ?? '',
				wins: r.wins ?? 0,
				losses: r.losses ?? 0,
				ties: r.ties ?? 0,
				wp: r.wp ?? 0,
				ap: r.ap ?? 0,
				sp: r.sp ?? 0
			};
		});

const mapSkills = (skills: Skill[], teams: Map<number, TeamLookup>): SkillsRow[] => {
	const agg = new Map<
		number,
		{ driver: number; auton: number; driverRuns: number; autonRuns: number }
	>();
	for (const skill of skills) {
		const id = skill.team?.id;
		if (!id) continue;
		const cur = agg.get(id) ?? { driver: 0, auton: 0, driverRuns: 0, autonRuns: 0 };
		const score = skill.score ?? 0;
		const attempts = skill.attempts ?? 0;
		if (skill.type === SkillType.Driver) {
			agg.set(id, {
				...cur,
				driver: Math.max(cur.driver, score),
				driverRuns: Math.max(cur.driverRuns, attempts)
			});
		} else if (skill.type === SkillType.Programming) {
			agg.set(id, {
				...cur,
				auton: Math.max(cur.auton, score),
				autonRuns: Math.max(cur.autonRuns, attempts)
			});
		}
	}
	return [...agg.entries()]
		.map(([id, a]) => {
			const team = teams.get(id);
			const points = a.driver + a.auton;
			return { team: team?.number ?? `${id}`, name: team?.name ?? '', points, ...a };
		})
		.sort((a, b) => b.points - a.points || b.driver - a.driver || b.auton - a.auton)
		.map((row, i) => ({ ...row, rank: i + 1 }));
};

export default function EventScreen() {
	const { id: idParam } = useLocalSearchParams<{ id: string }>();
	const eventId = parseInt(idParam ?? '', 10);

	const [loadingEvent, setLoadingEvent] = useState(false);
	const [loadingDivision, setLoadingDivision] = useState(false);
	const [loadError, setLoadError] = useState<string | null>(null);

	const [eventMeta, setEventMeta] = useState<Awaited<
		ReturnType<typeof re.events.eventGetEvent>
	> | null>(null);
	const [eventSku, setEventSku] = useState<string>('');
	const [divisions, setDivisions] = useState<(Division & { id: number })[]>([]);
	const [selectedDivisionId, setSelectedDivisionId] = useState<number | null>(null);
	const [teamLookup, setTeamLookup] = useState<Map<number, TeamLookup>>(new Map());
	const [allSkills, setAllSkills] = useState<Skill[]>([]);
	const [awards, setAwards] = useState<Award[]>([]);
	const [scheduleRows, setScheduleRows] = useState<ScheduleRow[]>([]);
	const [rankingRows, setRankingRows] = useState<RankingRow[]>([]);
	const [skillsRows, setSkillsRows] = useState<SkillsRow[]>([]);
	const [divisionMatches, setDivisionMatches] = useState<MatchObj[]>([]);
	const [infoData, setInfoData] = useState<EventInfo>(fallbackInfo);
	const [divisionSelectorOpen, setDivisionSelectorOpen] = useState(false);

	const [activeIndex, setActiveIndex] = useState(0);
	const tabScrollRef = useRef<ScrollView>(null);

	const [teamDrawerOpen, setTeamDrawerOpen] = useState(false);
	const [selectedTeam, setSelectedTeam] = useState<RankingRow | null>(null);
	const [matchDrawerOpen, setMatchDrawerOpen] = useState(false);
	const [selectedMatch, setSelectedMatch] = useState<ScheduleRow | null>(null);

	const divisionRatings = (() => {
		const quals = divisionMatches.filter((m) => m.round === 2);
		if (quals.length === 0) return null;
		return calculateOprDprCcwm(robotEventsMatchesToScoredMatches(quals, { includeUnscored: true }));
	})();

	const teamNumberToId = new Map<string, number>(
		[...teamLookup.entries()].map(([id, info]) => [info.number.toLowerCase(), id])
	);

	const normalize = (v: string) => v.trim().toLowerCase();

	const selectedTeamKey = selectedTeam ? normalize(selectedTeam.team) : null;
	const selectedTeamId = selectedTeamKey ? teamNumberToId.get(selectedTeamKey) : undefined;

	const selectedTeamRatings =
		divisionRatings && selectedTeamId !== undefined
			? {
					opr: divisionRatings.opr[selectedTeamId] ?? null,
					dpr: divisionRatings.dpr[selectedTeamId] ?? null,
					ccwm: divisionRatings.ccwm[selectedTeamId] ?? null
				}
			: { opr: null, dpr: null, ccwm: null };

	const selectedTeamSkills = selectedTeamKey
		? (skillsRows.find((r) => normalize(r.team) === selectedTeamKey) ?? null)
		: null;

	const selectedTeamMatches = selectedTeamKey
		? scheduleRows.filter(
				(r) =>
					r.red.some((t) => normalize(t) === selectedTeamKey) ||
					r.blue.some((t) => normalize(t) === selectedTeamKey)
			)
		: [];

	useEffect(() => {
		if (!Number.isFinite(eventId) || eventId <= 0) {
			setLoadError('Invalid event id.');
			return;
		}

		let cancelled = false;
		setLoadingEvent(true);
		setLoadError(null);

		(async () => {
			try {
				const [event, teams, skills, eventAwards] = await Promise.all([
					re.events.eventGetEvent({ id: eventId }),
					re.depaginate(
						re.events.eventGetTeams({ id: eventId }, re.custom.maxPages),
						re.models.PaginatedTeamFromJSON
					),
					re.depaginate(
						re.events.eventGetSkills({ id: eventId }, re.custom.maxPages),
						re.models.PaginatedSkillFromJSON
					),
					re
						.depaginate(
							re.events.eventGetAwards({ id: eventId }, re.custom.maxPages),
							re.models.PaginatedAwardFromJSON
						)
						.catch(() => [] as Award[])
				]);

				if (cancelled) return;

				const sortedDivs = [...(event.divisions ?? [])].sort(
					(a, b) => (a.order ?? 0) - (b.order ?? 0)
				) as (Division & { id: number })[];

				setEventMeta(event);
				setEventSku((event as any).sku ?? '');
				setDivisions(sortedDivs);
				setTeamLookup(buildTeamLookup(teams));
				setAllSkills(skills);
				setAwards(eventAwards);
				setInfoData(buildInfoData(event, sortedDivs[0]?.name ?? 'Division'));

				const firstDiv = sortedDivs[0];
				if (firstDiv) setSelectedDivisionId(firstDiv.id);
			} catch (e) {
				if (!cancelled) setLoadError((e as Error).message || 'Unable to load event data.');
			} finally {
				if (!cancelled) setLoadingEvent(false);
			}
		})();

		return () => {
			cancelled = true;
		};
	}, [eventId]);

	useEffect(() => {
		if (!eventMeta || selectedDivisionId === null) return;

		const divName = divisions.find((d) => d.id === selectedDivisionId)?.name ?? 'Division';
		setInfoData(buildInfoData(eventMeta, divName));

		const filtered = allSkills.filter((s) => s.division?.id === selectedDivisionId);
		setSkillsRows(mapSkills(filtered.length > 0 ? filtered : allSkills, teamLookup));

		let cancelled = false;
		setLoadingDivision(true);

		(async () => {
			try {
				const [rankings, matches] = await Promise.all([
					re.depaginate(
						re.events.eventGetDivisionRankings(
							{ id: eventId, div: selectedDivisionId },
							re.custom.maxPages
						),
						re.models.PaginatedRankingFromJSON
					),
					re.depaginate(
						re.events.eventGetDivisionMatches(
							{ id: eventId, div: selectedDivisionId },
							re.custom.maxPages
						),
						re.models.PaginatedMatchFromJSON
					)
				]);

				if (cancelled) return;
				setRankingRows(mapRankings(rankings, teamLookup));
				setScheduleRows(mapMatches(matches));
				setDivisionMatches(matches);
			} catch (e) {
				if (!cancelled) setLoadError((e as Error).message || 'Unable to load division data.');
			} finally {
				if (!cancelled) setLoadingDivision(false);
			}
		})();

		return () => {
			cancelled = true;
		};
	}, [eventId, selectedDivisionId, eventMeta]);

	const goToTab = (index: number) => {
		setActiveIndex(index);
		tabScrollRef.current?.scrollTo({ x: index * SCREEN_WIDTH, animated: true });
	};

	const onScrollEnd = (e: NativeSyntheticEvent<NativeScrollEvent>) => {
		const index = Math.round(e.nativeEvent.contentOffset.x / SCREEN_WIDTH);
		setActiveIndex(index);
	};

	const openTeamDrawer = (row: RankingRow) => {
		setSelectedTeam(row);
		setTeamDrawerOpen(true);
	};

	const openMatchDrawer = (row: ScheduleRow) => {
		setSelectedMatch(row);
		setMatchDrawerOpen(true);
	};

	const isLoading = loadingEvent || loadingDivision;

	const selectedDivisionName =
		divisions.find((d) => d.id === selectedDivisionId)?.name ?? 'Division';

	const teamEntries = [...teamLookup.entries()].map(([id, t]) => ({
		id,
		number: t.number,
		name: t.name
	}));

	return (
		<SafeAreaView style={styles.safe} edges={['top']}>
			<View style={styles.topBar}>
				<TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
					<ArrowLeft size={24} color={colors.foreground} />
				</TouchableOpacity>
				<TouchableOpacity
					style={styles.divisionSelector}
					onPress={() => divisions.length > 1 && setDivisionSelectorOpen(true)}
				>
					<Users size={16} color={colors.mutedForeground} />
					<Text style={styles.divisionText}>{selectedDivisionName}</Text>
				</TouchableOpacity>
			</View>

			{isLoading && (
				<View style={styles.loadingBar}>
					<ActivityIndicator size="small" color={colors.primary} />
				</View>
			)}

			{loadError && (
				<View style={styles.errorBox}>
					<Text style={styles.errorText}>{loadError}</Text>
				</View>
			)}

			<View style={styles.tabBar}>
				{tabMeta.map((tab, i) => {
					const Icon = tab.icon;
					const active = activeIndex === i;
					return (
						<TouchableOpacity
							key={tab.key}
							style={[styles.tabBtn, active && styles.tabBtnActive]}
							onPress={() => goToTab(i)}
						>
							<Icon
								size={22}
								color={active ? colors.primary : colors.mutedForeground}
								strokeWidth={2.25}
							/>
						</TouchableOpacity>
					);
				})}
			</View>

			<ScrollView
				ref={tabScrollRef}
				horizontal
				pagingEnabled
				showsHorizontalScrollIndicator={false}
				scrollEventThrottle={16}
				onMomentumScrollEnd={onScrollEnd}
				style={styles.tabPages}
				decelerationRate="fast"
			>
				<ScrollView style={styles.tabPage} contentContainerStyle={styles.tabContent}>
					<ScheduleTab rows={scheduleRows} onMatchSelect={openMatchDrawer} />
				</ScrollView>
				<ScrollView style={styles.tabPage} contentContainerStyle={styles.tabContent}>
					<RankingsTab rows={rankingRows} onTeamSelect={openTeamDrawer} />
				</ScrollView>
				<ScrollView style={styles.tabPage} contentContainerStyle={styles.tabContent}>
					<SkillsTab rows={skillsRows} />
				</ScrollView>
				<ScrollView style={styles.tabPage} contentContainerStyle={styles.tabContent}>
					<InfoTab
						info={infoData}
						teams={teamEntries}
						awards={awards}
						rankingRows={rankingRows}
						hasSchedule={scheduleRows.length > 0}
						season={eventMeta?.season?.id ?? 0}
						onTeamSelect={openTeamDrawer}
						sku={eventSku}
					/>
				</ScrollView>
			</ScrollView>

			{divisions.length > 1 && divisionSelectorOpen && (
				<View style={styles.divDropdown}>
					{divisions.map((div) => (
						<TouchableOpacity
							key={div.id}
							style={[styles.divOption, div.id === selectedDivisionId && styles.divOptionActive]}
							onPress={() => {
								setSelectedDivisionId(div.id);
								setDivisionSelectorOpen(false);
							}}
						>
							<Text
								style={[
									styles.divOptionText,
									div.id === selectedDivisionId && styles.divOptionTextActive
								]}
							>
								{div.name}
							</Text>
						</TouchableOpacity>
					))}
				</View>
			)}

			<TeamDrawer
				open={teamDrawerOpen}
				onClose={() => setTeamDrawerOpen(false)}
				team={selectedTeam}
				skills={selectedTeamSkills}
				matches={selectedTeamMatches}
				opr={selectedTeamRatings.opr}
				dpr={selectedTeamRatings.dpr}
				ccwm={selectedTeamRatings.ccwm}
			/>
			<MatchDrawer
				open={matchDrawerOpen}
				onClose={() => setMatchDrawerOpen(false)}
				row={selectedMatch}
				rankingRows={rankingRows}
			/>
		</SafeAreaView>
	);
}

const styles = StyleSheet.create({
	safe: { flex: 1, backgroundColor: colors.background },
	topBar: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: spacing.md,
		paddingVertical: 8
	},
	backBtn: {
		width: 40,
		height: 40,
		borderRadius: 20,
		alignItems: 'center',
		justifyContent: 'center'
	},
	divisionSelector: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		backgroundColor: colors.card,
		borderRadius: radius.lg,
		borderWidth: 1,
		borderColor: colors.border,
		paddingHorizontal: 12,
		paddingVertical: 7
	},
	divisionText: { fontSize: font.sm, color: colors.foreground },
	loadingBar: {
		paddingVertical: 4,
		paddingHorizontal: spacing.md,
		alignItems: 'flex-start'
	},
	errorBox: {
		marginHorizontal: spacing.md,
		marginBottom: 8,
		backgroundColor: colors.destructive + '20',
		borderRadius: radius.md,
		padding: spacing.md
	},
	errorText: { color: colors.destructive, fontSize: font.sm },
	tabBar: {
		flexDirection: 'row',
		backgroundColor: colors.card,
		borderTopWidth: 1,
		borderTopColor: colors.border,
		marginHorizontal: spacing.md,
		borderRadius: radius.xl,
		borderWidth: 1,
		borderColor: colors.border,
		overflow: 'hidden'
	},
	tabBtn: { flex: 1, height: 48, alignItems: 'center', justifyContent: 'center' },
	tabBtnActive: { backgroundColor: colors.primary + '25' },
	tabPages: { flex: 1, marginTop: 8 },
	tabPage: { width: SCREEN_WIDTH },
	tabContent: {
		paddingHorizontal: spacing.md,
		paddingTop: spacing.md,
		paddingBottom: spacing['3xl']
	},
	divDropdown: {
		position: 'absolute',
		top: 60,
		right: spacing.md,
		backgroundColor: colors.card,
		borderRadius: radius.lg,
		borderWidth: 1,
		borderColor: colors.border,
		overflow: 'hidden',
		zIndex: 100,
		minWidth: 160
	},
	divOption: { paddingHorizontal: 16, paddingVertical: 12 },
	divOptionActive: { backgroundColor: colors.primary + '20' },
	divOptionText: { fontSize: font.base, color: colors.foreground },
	divOptionTextActive: { color: colors.primary, fontWeight: '500' }
});
