// src/routes/events/[id]/MatchDrawer.svelte
<script lang="ts">
	import * as Drawer from '$lib/components/ui/drawer';

	type ScheduleRow = {
		group: 'practice' | 'qualifier' | 'elimination';
		match: string;
		time: string;
		score: string;
		red: string[];
		blue: string[];
		field?: string;
		played: boolean;
	};

	type RankingRow = {
		rank: number;
		team: string;
		name: string;
		wins: number;
		losses: number;
		ties: number;
		wp: number;
		ap: number;
		sp: number;
	};

	interface Props {
		open?: boolean;
		row: ScheduleRow | null;
		rankingRows: RankingRow[];
	}

	let { open = $bindable(false), row, rankingRows }: Props = $props();

	const normalizeTeam = (value: string) => value.trim().toLowerCase();

	const parseScores = (score: string): [number, number] => {
		const [leftRaw = '0', rightRaw = '0'] = score.split('-');
		const left = Number.parseInt(leftRaw.trim(), 10);
		const right = Number.parseInt(rightRaw.trim(), 10);
		return [Number.isNaN(left) ? 0 : left, Number.isNaN(right) ? 0 : right];
	};

	let scores = $derived(row ? parseScores(row.score) : ([0, 0] as [number, number]));
	let redScore = $derived(scores[0]);
	let blueScore = $derived(scores[1]);

	const getTeamRanking = (teamNumber: string) =>
		rankingRows.find((r) => normalizeTeam(r.team) === normalizeTeam(teamNumber)) ?? null;
</script>

<Drawer.Root bind:open>
	<Drawer.Content scrollable>
		{#if row}
			<div class="space-y-5">
				<Drawer.Header class="px-0 pb-0 text-left">
					<Drawer.Title class="text-2xl leading-none font-semibold tracking-tight">
						Game Info
					</Drawer.Title>
				</Drawer.Header>

				<div class="rounded-2xl bg-red-950 p-5 text-foreground">
					<div class="text-6xl leading-none font-medium [font-variant-numeric:tabular-nums]">
						{row.match}
					</div>
					<div class="mt-1.5 text-sm text-foreground/60">
						{row.played ? 'Played' : 'Scheduled'}
					</div>

					<div class="mt-5 space-y-1.5 text-sm">
						<div class="flex justify-between gap-4">
							<span class="text-foreground/60">Start Time</span>
							<span class="font-medium">{row.time}</span>
						</div>
						{#if row.field}
							<div class="flex justify-between gap-4">
								<span class="shrink-0 text-foreground/60">Field</span>
								<span class="text-right font-medium">{row.field}</span>
							</div>
						{/if}
					</div>
				</div>

				<div>
					<div class="mb-2 flex items-baseline justify-between">
						<span class="text-xl font-medium">Red Alliance</span>
						<span class="text-5xl leading-none font-medium [font-variant-numeric:tabular-nums]">
							{redScore}
						</span>
					</div>
					{#each row.red as teamNumber}
						{@const ranking = getTeamRanking(teamNumber)}
						<div class="flex items-center gap-3 border-t border-border/60 py-3">
							<div
								class="w-7 shrink-0 text-right text-sm text-muted-foreground [font-variant-numeric:tabular-nums]"
							>
								{ranking?.rank ?? ''}
							</div>
							<div class="min-w-0 flex-1">
								<div
									class="text-3xl leading-none font-medium text-red-300 [font-variant-numeric:tabular-nums]"
								>
									{teamNumber}
								</div>
								{#if ranking?.name}
									<div class="mt-0.5 text-xs text-muted-foreground">{ranking.name}</div>
								{/if}
							</div>
							{#if ranking}
								<div class="flex text-xs [font-variant-numeric:tabular-nums]">
									<div class="pr-3 text-right">
										<div>{ranking.wins}-{ranking.losses}-{ranking.ties}</div>
										<div class="text-muted-foreground">{ranking.wp} WP</div>
									</div>
									<div class="border-l border-border/50 pl-3 text-right">
										<div>{ranking.ap} AP</div>
										<div class="text-muted-foreground">{ranking.sp} SP</div>
									</div>
								</div>
							{/if}
						</div>
					{/each}
				</div>

				<div>
					<div class="mb-2 flex items-baseline justify-between">
						<span class="text-xl font-medium">Blue Alliance</span>
						<span class="text-5xl leading-none font-medium [font-variant-numeric:tabular-nums]">
							{blueScore}
						</span>
					</div>
					{#each row.blue as teamNumber}
						{@const ranking = getTeamRanking(teamNumber)}
						<div class="flex items-center gap-3 border-t border-border/60 py-3">
							<div
								class="w-7 shrink-0 text-right text-sm text-muted-foreground [font-variant-numeric:tabular-nums]"
							>
								{ranking?.rank ?? ''}
							</div>
							<div class="min-w-0 flex-1">
								<div
									class="text-3xl leading-none font-medium text-blue-300 [font-variant-numeric:tabular-nums]"
								>
									{teamNumber}
								</div>
								{#if ranking?.name}
									<div class="mt-0.5 text-xs text-muted-foreground">{ranking.name}</div>
								{/if}
							</div>
							{#if ranking}
								<div class="flex text-xs [font-variant-numeric:tabular-nums]">
									<div class="pr-3 text-right">
										<div>{ranking.wins}-{ranking.losses}-{ranking.ties}</div>
										<div class="text-muted-foreground">{ranking.wp} WP</div>
									</div>
									<div class="border-l border-border/50 pl-3 text-right">
										<div>{ranking.ap} AP</div>
										<div class="text-muted-foreground">{ranking.sp} SP</div>
									</div>
								</div>
							{/if}
						</div>
					{/each}
					<div class="border-t border-border/60"></div>
				</div>
			</div>
		{/if}
	</Drawer.Content>
</Drawer.Root>

// scoutr-vrc/lib/components/events/MatchDrawer.tsx
import { View, Text, ScrollView, Modal, Pressable, StyleSheet } from 'react-native';
import { colors, font, radius, spacing } from '../../theme';

type ScheduleRow = {
	group: 'practice' | 'qualifier' | 'elimination';
	match: string;
	time: string;
	score: string;
	red: string[];
	blue: string[];
	field?: string;
	played: boolean;
};

type RankingRow = {
	rank: number;
	team: string;
	name: string;
	wins: number;
	losses: number;
	ties: number;
	wp: number;
	ap: number;
	sp: number;
};

interface Props {
	open: boolean;
	onClose: () => void;
	row: ScheduleRow | null;
	rankingRows: RankingRow[];
}

const parseScores = (score: string): [number, number] => {
	const [l = '0', r = '0'] = score.split('-');
	const left = parseInt(l.trim(), 10);
	const right = parseInt(r.trim(), 10);
	return [isNaN(left) ? 0 : left, isNaN(right) ? 0 : right];
};

const normalize = (v: string) => v.trim().toLowerCase();

export const MatchDrawer = ({ open, onClose, row, rankingRows }: Props) => {
	if (!row) return null;

	const [redScore, blueScore] = parseScores(row.score);
	const getTeamRanking = (teamNumber: string) =>
		rankingRows.find((r) => normalize(r.team) === normalize(teamNumber)) ?? null;

	const AllianceTeam = ({ teamNumber, color }: { teamNumber: string; color: string }) => {
		const ranking = getTeamRanking(teamNumber);
		return (
			<View style={styles.allianceTeamRow}>
				<Text style={styles.rankLabel}>{ranking?.rank ?? ''}</Text>
				<View style={{ flex: 1, minWidth: 0 }}>
					<Text style={[styles.teamNum, { color }]}>{teamNumber}</Text>
					{ranking?.name ? <Text style={styles.teamName}>{ranking.name}</Text> : null}
				</View>
				{ranking && (
					<View style={styles.rankStats}>
						<View style={styles.statGroup}>
							<Text style={styles.statLine}>
								{ranking.wins}-{ranking.losses}-{ranking.ties}
							</Text>
							<Text style={styles.statMuted}>{ranking.wp} WP</Text>
						</View>
						<View style={styles.divider} />
						<View style={styles.statGroupRight}>
							<Text style={styles.statLine}>{ranking.ap} AP</Text>
							<Text style={styles.statMuted}>{ranking.sp} SP</Text>
						</View>
					</View>
				)}
			</View>
		);
	};

	return (
		<Modal visible={open} transparent animationType="slide" onRequestClose={onClose}>
			<Pressable style={styles.backdrop} onPress={onClose} />
			<View style={styles.sheet}>
				<View style={styles.handle} />
				<ScrollView showsVerticalScrollIndicator={false}>
					<Text style={styles.heading}>Game Info</Text>

					<View style={styles.matchCard}>
						<Text style={styles.matchName}>{row.match}</Text>
						<Text style={styles.matchStatus}>{row.played ? 'Played' : 'Scheduled'}</Text>
						<View style={styles.matchMeta}>
							<Text style={styles.matchMetaLabel}>Start Time</Text>
							<Text style={styles.matchMetaVal}>{row.time}</Text>
						</View>
						{row.field && (
							<View style={[styles.matchMeta, { marginTop: 4 }]}>
								<Text style={styles.matchMetaLabel}>Field</Text>
								<Text style={styles.matchMetaVal}>{row.field}</Text>
							</View>
						)}
					</View>

					<View style={styles.allianceSection}>
						<View style={styles.allianceHeader}>
							<Text style={styles.allianceTitle}>Red Alliance</Text>
							<Text style={styles.bigScore}>{redScore}</Text>
						</View>
						{row.red.map((team, i) => (
							<AllianceTeam key={i} teamNumber={team} color="#fca5a5" />
						))}
					</View>

					<View style={styles.allianceSection}>
						<View style={styles.allianceHeader}>
							<Text style={styles.allianceTitle}>Blue Alliance</Text>
							<Text style={styles.bigScore}>{blueScore}</Text>
						</View>
						{row.blue.map((team, i) => (
							<AllianceTeam key={i} teamNumber={team} color="#93c5fd" />
						))}
						<View style={{ height: 1, backgroundColor: colors.border }} />
					</View>

					<View style={{ height: 32 }} />
				</ScrollView>
			</View>
		</Modal>
	);
};

const styles = StyleSheet.create({
	backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
	sheet: {
		backgroundColor: colors.card,
		borderTopLeftRadius: 24,
		borderTopRightRadius: 24,
		padding: spacing.lg,
		paddingBottom: 0,
		maxHeight: '85%'
	},
	handle: {
		width: 36,
		height: 4,
		borderRadius: 2,
		backgroundColor: colors.border,
		alignSelf: 'center',
		marginBottom: 16
	},
	heading: { fontSize: font['2xl'], fontWeight: '600', color: colors.foreground, marginBottom: 16 },
	matchCard: {
		backgroundColor: '#450a0a',
		borderRadius: radius.xl,
		padding: spacing.lg,
		marginBottom: 20
	},
	matchName: { fontSize: font['5xl'], fontWeight: '500', color: colors.foreground, lineHeight: 56 },
	matchStatus: { fontSize: font.sm, color: 'rgba(255,255,255,0.5)', marginBottom: 16 },
	matchMeta: { flexDirection: 'row', justifyContent: 'space-between' },
	matchMetaLabel: { fontSize: font.sm, color: 'rgba(255,255,255,0.5)' },
	matchMetaVal: { fontSize: font.sm, fontWeight: '500', color: colors.foreground },
	allianceSection: { marginBottom: 16 },
	allianceHeader: {
		flexDirection: 'row',
		alignItems: 'baseline',
		justifyContent: 'space-between',
		marginBottom: 8
	},
	allianceTitle: { fontSize: font.xl, fontWeight: '500', color: colors.foreground },
	bigScore: {
		fontSize: font['5xl'],
		fontWeight: '500',
		color: colors.foreground,
		fontVariant: ['tabular-nums']
	},
	allianceTeamRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
		borderTopWidth: 1,
		borderTopColor: colors.border,
		paddingVertical: 12
	},
	rankLabel: {
		width: 24,
		fontSize: font.sm,
		color: colors.mutedForeground,
		textAlign: 'right',
		fontVariant: ['tabular-nums']
	},
	teamNum: {
		fontSize: font['3xl'],
		fontWeight: '500',
		fontVariant: ['tabular-nums'],
		lineHeight: 36
	},
	teamName: { fontSize: font.xs, color: colors.mutedForeground, marginTop: 2 },
	rankStats: { flexDirection: 'row', alignItems: 'center', gap: 8 },
	statGroup: { alignItems: 'flex-start', gap: 2 },
	statGroupRight: { alignItems: 'flex-end', gap: 2 },
	statLine: { fontSize: font.xs, color: colors.foreground, fontVariant: ['tabular-nums'] },
	statMuted: { fontSize: font.xs, color: colors.mutedForeground, fontVariant: ['tabular-nums'] },
	divider: { width: 1, height: 28, backgroundColor: colors.border }
});
