// src/routes/events/[id]/ScheduleTab.svelte
<script lang="ts">
	import { ChevronDown } from '@lucide/svelte';
	import MatchRow from './MatchRow.svelte';

	type ScheduleRow = {
		group: 'practice' | 'qualifier' | 'elimination';
		match: string;
		time: string;
		score: string;
		red: string[];
		blue: string[];
		field?: string;
		played: boolean;
	};

	type ScheduleGroup = ScheduleRow['group'];

	let { rows, onMatchSelect }: { rows: ScheduleRow[]; onMatchSelect?: (row: ScheduleRow) => void } =
		$props();

	let expandedGroups = $state<Record<ScheduleGroup, boolean>>({
		practice: true,
		qualifier: true,
		elimination: true
	});

	const groupedRows = $derived([
		{
			key: 'practice' as const,
			title: 'Practice',
			rows: rows.filter((row) => row.group === 'practice')
		},
		{
			key: 'qualifier' as const,
			title: 'Qualifications',
			rows: rows.filter((row) => row.group === 'qualifier')
		},
		{
			key: 'elimination' as const,
			title: 'Eliminations',
			rows: rows.filter((row) => row.group === 'elimination')
		}
	]);
</script>

<div class="space-y-4">
	{#each groupedRows as section}
		{#if section.rows.length > 0}
			<div class="space-y-1">
				<button
					type="button"
					onclick={() => (expandedGroups[section.key] = !expandedGroups[section.key])}
					class="mb-2 flex w-full items-center gap-2 text-left text-lg leading-none font-semibold"
				>
					<span>{section.title}</span>
					<ChevronDown
						class="h-5 w-5 text-muted-foreground transition-transform {expandedGroups[section.key]
							? 'rotate-0'
							: '-rotate-90'}"
					/>
				</button>

				{#if expandedGroups[section.key]}
					{#each section.rows as row}
						<button type="button" onclick={() => onMatchSelect?.(row)} class="w-full text-left">
							<MatchRow {row} />
						</button>
					{/each}
				{/if}
			</div>
		{/if}
	{/each}
</div>

// scoutr-vrc/lib/components/events/ScheduleTab.tsx
import { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import { ChevronDown } from 'lucide-react-native';
import { colors, font } from '../../theme';
import { MatchRow } from './MatchRow';

type ScheduleRow = {
  group: 'practice' | 'qualifier' | 'elimination';
  match: string;
  time: string;
  score: string;
  red: string[];
  blue: string[];
  field?: string;
  played: boolean;
};

type ScheduleGroup = ScheduleRow['group'];

interface Props {
  rows: ScheduleRow[];
  onMatchSelect?: (row: ScheduleRow) => void;
}

export const ScheduleTab = ({ rows, onMatchSelect }: Props) => {
  const [expanded, setExpanded] = useState<Record<ScheduleGroup, boolean>>({
    practice: true,
    qualifier: true,
    elimination: true,
  });

  const groups: { key: ScheduleGroup; title: string }[] = [
    { key: 'practice', title: 'Practice' },
    { key: 'qualifier', title: 'Qualifications' },
    { key: 'elimination', title: 'Eliminations' },
  ];

  return (
    <View style={styles.container}>
      {groups.map(({ key, title }) => {
        const sectionRows = rows.filter((r) => r.group === key);
        if (sectionRows.length === 0) return null;
        const isOpen = expanded[key];
        return (
          <View key={key} style={styles.section}>
            <TouchableOpacity
              style={styles.sectionHeader}
              onPress={() => setExpanded((prev) => ({ ...prev, [key]: !prev[key] }))}
            >
              <Text style={styles.sectionTitle}>{title}</Text>
              <ChevronDown
                size={18}
                color={colors.mutedForeground}
                style={{ transform: [{ rotate: isOpen ? '0deg' : '-90deg' }] }}
              />
            </TouchableOpacity>
            {isOpen &&
              sectionRows.map((row, i) => (
                <TouchableOpacity key={i} onPress={() => onMatchSelect?.(row)}>
                  <MatchRow row={row} />
                </TouchableOpacity>
              ))}
          </View>
        );
      })}
    </View>
  );
};

const styles = StyleSheet.create({
  container: { gap: 16 },
  section: { gap: 4 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  sectionTitle: { fontSize: font.lg, fontWeight: '600', color: colors.foreground },
});
